apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  selector:
    app: backend
{{- if eq .Values.backend.serviceType "NodePort" }}
  type: NodePort
{{- else }}
  type: ClusterIP
{{- end }}
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      {{- if eq .Values.backend.serviceType "NodePort" }}
      nodePort: {{ .Values.backend.nodePort }}
      {{- end }}


