{{- if eq .Values.frontend.service.type "NodePort" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-chart.fullname" . }}
spec:
  selector:
    app: frontend
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
{{- else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-chart.fullname" . }}
spec:
  selector:
    app: frontend
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
{{- end }}


